@startuml
!include ../style.puml

box <font color=black>Logic
participant ":LogicManager" as LogicManager LOGIC_COLOR_T5
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR_T5
participant ":HighImportanceCommandParser" as HighImportanceCommandParser LOGIC_COLOR_T5
participant "h :HighImportanceCommand" as HighImportanceCommand LOGIC_COLOR_T5
participant ":CommandResult" as CommandResult LOGIC_COLOR_T5

-> LogicManager : execute("impt 1")
activate LogicManager

LogicManager -> AddressBookParser: parseCommand("impt 1")
activate AddressBookParser

create HighImportanceCommandParser
AddressBookParser -> HighImportanceCommandParser ++

HighImportanceCommandParser --> AddressBookParser --

AddressBookParser -> HighImportanceCommandParser ++ : \nparse("1")

create HighImportanceCommand
HighImportanceCommandParser -> HighImportanceCommand ++

HighImportanceCommand --> HighImportanceCommandParser -- : h
HighImportanceCommandParser --> AddressBookParser -- : h
destroy HighImportanceCommandParser

AddressBookParser --> LogicManager -- : h
LogicManager -> HighImportanceCommand ++ : execute()

box <font color=black>Model MODEL_COLOR_T1
participant "<font color=white>:Model" as model MODEL_COLOR_T4
participant "<font color=white>personList:List" as personList MODEL_COLOR_T4
end box

HighImportanceCommand -> model ++ : getSortedPersonList()
model --> HighImportanceCommand : personList
deactivate model

HighImportanceCommand -> personList ++ : get(2)
personList --> HighImportanceCommand : targetPerson
deactivate personList

HighImportanceCommand -> HighImportanceCommand ++ : createHighImportancePerson(targetPerson, HIGH_IMPORTANCE)
HighImportanceCommand --> HighImportanceCommand : editedPerson
deactivate HighImportanceCommand

HighImportanceCommand -> model ++ : setPerson(targetPerson, editedPerson)
model --> HighImportanceCommand
deactivate model

create CommandResult
HighImportanceCommand -> CommandResult ++
CommandResult --> HighImportanceCommand --

HighImportanceCommand --> LogicManager
deactivate HighImportanceCommand
destroy HighImportanceCommand
<-- LogicManager

@enduml
