@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package List<Person> {
Class "List[index - 1]" as Person1
Class "List[index]" as Person2
Class "List[index + 1]" as Person3
Class "editedPerson" as Person4
}


Person1 - Person2
Person2 - Person3

class Pointer as "personToAddDeadline"
Pointer -up-> Person2
@enduml